
/*! \file defs.grmhd.h
    \brief Wrapper
*/
/*! \file decs.grmhd.h
    \brief AUTOGENERATED from defs.grmhd.h
*/

#include "global.grmhd.h"
#include "superdefs.h"
#include "superdefs.pointers.h"
#include "defs.general.h"
