
/*! \file defs.user.h
    \brief User type defs (but better to use init.c and extern unless for coord.c)
*/
/*! \file decs.user.h
    \brief AUTOGENERATED from defs.user.h
*/

///Coordinates holder
///GODMARK: don't know how to use FTYPE here -- FTYPE defined in global.h 
/// need not static so other files can access settings
struct Ccoordparams coordparams;
