
/*! \file global.h
    \brief AUTOGENERATED from global.grmhd.h
*/

/*! \file global.grmhd.h
    \brief Wrapper and Comments on comments

  Generally, switches that are performance related are here, while others are in init with variable complements for flexibility during runtime.

  Not everything is in here so can compile quicker on simple changes.

/////////////////////////////////////////
//
// Comments on comments
//
//////////////////////////////////////////

//
// CHANGINGMARK: Most recent changes or issues
//
// GODMARK: Generally needs consideration but may not be crucial
//
// SUPERGODMARK: Needs urgent attention or workaround
//
// SUPERMARK: Something changing
//
// SASMARK: Changes by Sasha
//
// SECTIONMARK: Issue/Comment with regards to grid sectioning
//
// TESTMARK: Something was/is for testing purposes only
//
// NEWMARK: New code in development
//
// **TODO** : Things to do in code
//
// GLOBALMARK: Location where global positional array is used
//
// ISSUESMARK: List of known issues of importance
//
// USAGEMARK: Notes on usage of code
//
// OPTMARK: Comment about performance optimizations
//
// SUPERNOTE: Important note should consider anytime in that file
//
// OPENMPNOTE: Note related to OpenMP
//
// OPENMPOPTMARK: Optimization note or suggestion
//
/////////////////////////////////////////




// Ensure to test for external declaration consistency using checkexterns.sh.  See end of global.general.h


// See also the files:
// docs/
// bbcp and file transfer info: bbcp.txt
// code-system optimization info: optimizations.txt
// MPI and OPENMP info: parallel.txt
// svnand git info: svngit.txt
// debug info: debug.txt
//
    
*/

#define DOINGGRMHDTYPECODE 1 // always 1
#define DOINGGRRAYTYPECODE 0 // always 0
#define DOINGLIAISONTYPECODE 0 // always 0
#include "global.general.h"












