// THIS IS AN AUTOGENERATED FILE, DO NOT MODIFY



#define MAXNPR 9
#define NPR 9
#define NPRREALSET 8
#define NPRBOUND 8
#define NPRDUMP 8
#define NFLUXBOUND 9
#define NPR2INTERP 9
#define NPRINVERT 5
#define YL -100
#define YNU -100
#define ENTROPY 8
#define VSQ -100
