



// THIS IS AN AUTOGENERATED FILE, DO NOT MODIFY



void set_default_nprlists(void)
{

int pl,pliter;



nprstart=0; nprend=8;
nprlist[0]=0;
nprlist[1]=1;
nprlist[2]=2;
nprlist[3]=3;
nprlist[4]=4;
nprlist[5]=5;
nprlist[6]=6;
nprlist[7]=7;
nprlist[8]=8;

npr2interpstart=0; npr2interpend=7;
npr2interplist[0]=0;
npr2interplist[1]=1;
npr2interplist[2]=2;
npr2interplist[3]=3;
npr2interplist[4]=4;
npr2interplist[5]=5;
npr2interplist[6]=6;
npr2interplist[7]=7;

npr2notinterpstart=0; npr2notinterpend=-1;

nprboundstart=0; nprboundend=7;
nprboundlist[0]=0;
nprboundlist[1]=1;
nprboundlist[2]=2;
nprboundlist[3]=3;
nprboundlist[4]=4;
nprboundlist[5]=5;
nprboundlist[6]=6;
nprboundlist[7]=7;

nprfluxboundstart=0; nprfluxboundend=8;
nprfluxboundlist[0]=0;
nprfluxboundlist[1]=1;
nprfluxboundlist[2]=2;
nprfluxboundlist[3]=3;
nprfluxboundlist[4]=4;
nprfluxboundlist[5]=5;
nprfluxboundlist[6]=6;
nprfluxboundlist[7]=7;
nprfluxboundlist[8]=8;

nprdumpstart=0; nprdumpend=7;
nprdumplist[0]=0;
nprdumplist[1]=1;
nprdumplist[2]=2;
nprdumplist[3]=3;
nprdumplist[4]=4;
nprdumplist[5]=5;
nprdumplist[6]=6;
nprdumplist[7]=7;

nprinvertstart=0; nprinvertend=4;
nprinvertlist[0]=0;
nprinvertlist[1]=1;
nprinvertlist[2]=2;
nprinvertlist[3]=3;
nprinvertlist[4]=4;



}


