////////////////////////////////////
//
// Allocate space and setup pointers for EOS tablea
//
///////////////////////////////////////////////
//
// This entire file assumes all things are FTYPE except eostable itself that is explicitly FTYPEEOS
//
///////////////////////////////////////////////

// presumed to be several functions as functions of 4 other quantities that are the independent variables (UEOS,PEOS,CHIEOS share same index)
// Notice that eostable has density as EOS*N1 so fastest indicies are related to density and pressure-related quantities since this will result in fastest lookup for fixed H and Tdynorye
// due to float limit of 1E38, need FTYPEEOSs
// ,1,EOS??N5, at front is so table array uniform with degen table array



// SUPERNOTE: Also change things in kazfulleos_set_arrays.c!  For that, can just take below BASEEOSMAC stuff and regexp one's way to required format as given in that C file.
// SUPERNOTE: Must create corresponding MPI_Bcast() for these in kazfulleos_read_setup_eostable.c !!

// most of the below is simple mod from copy/paste of first "full" table block

#if(WHICHEOS==KAZFULL)

// full
FTYPEEOS BASEEOSMAC(eosfulltabledegen,NUMEOSDEGENQUANTITIESMEM1,EOSFULLDEGENN5,EOSFULLDEGENN4,EOSFULLDEGENN3,EOSFULLDEGENN2,EOSFULLDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
FTYPEEOS BASEEOSMAC(eosfulltablestandard,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSSTANDARDQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eosfulltableguess,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSGUESSQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eosfulltablediss,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSDISSQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eosfulltabledp,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSDPQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eosfulltablesden,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSSDENQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eosfulltablesspec,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSSSPECQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eosfulltablepofchi,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSPOFCHIQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eosfulltabletemp,NUMEOSTEMPQUANTITIESMEM1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSTEMPQUANTITIESMEM2);

// different size for extra table
FTYPEEOS BASEEOSMAC(eosfulltableextra,1,EOSEXTRAFULLN5,EOSEXTRAFULLN4,EOSEXTRAFULLN3,EOSEXTRAFULLN2,EOSEXTRAFULLN1,NUMEOSEXTRAQUANTITIESMEM);
#if(WHICHDATATYPEGENERAL==4)
FTYPEEOS BASEEOSMAC(eosfulltableextradegen,NUMEOSDEGENQUANTITIESMEM1,EOSEXTRAFULLDEGENN5,EOSEXTRAFULLDEGENN4,EOSEXTRAFULLDEGENN3,EOSEXTRAFULLDEGENN2,EOSEXTRAFULLDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
FTYPEEOS BASEEOSMAC(eosfulltableextratemp,NUMEOSTEMPQUANTITIESMEM1,EOSEXTRAFULLTEMPN5,EOSEXTRAFULLTEMPN4,EOSEXTRAFULLTEMPN3,EOSEXTRAFULLTEMPN2,EOSEXTRAFULLTEMPN1,NUMEOSTEMPQUANTITIESMEM2);
#endif

// simple
FTYPEEOS BASEEOSMAC(eossimpletabledegen,NUMEOSDEGENQUANTITIESMEM1,EOSSIMPLEDEGENN5,EOSSIMPLEDEGENN4,EOSSIMPLEDEGENN3,EOSSIMPLEDEGENN2,EOSSIMPLEDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
FTYPEEOS BASEEOSMAC(eossimpletablestandard,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSSTANDARDQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimpletableguess,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSGUESSQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimpletablediss,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSDISSQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimpletabledp,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSDPQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimpletablesden,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSSDENQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimpletablesspec,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSSSPECQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimpletablepofchi,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSPOFCHIQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimpletabletemp,NUMEOSTEMPQUANTITIESMEM1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSTEMPQUANTITIESMEM2);

// different size for extra table
FTYPEEOS BASEEOSMAC(eossimpletableextra,1,EOSEXTRASIMPLEN5,EOSEXTRASIMPLEN4,EOSEXTRASIMPLEN3,EOSEXTRASIMPLEN2,EOSEXTRASIMPLEN1,NUMEOSEXTRAQUANTITIESMEM);
#if(WHICHDATATYPEGENERAL==4)
FTYPEEOS BASEEOSMAC(eossimpletableextradegen,NUMEOSDEGENQUANTITIESMEM1,EOSEXTRASIMPLEDEGENN5,EOSEXTRASIMPLEDEGENN4,EOSEXTRASIMPLEDEGENN3,EOSEXTRASIMPLEDEGENN2,EOSEXTRASIMPLEDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
FTYPEEOS BASEEOSMAC(eossimpletableextratemp,NUMEOSTEMPQUANTITIESMEM1,EOSEXTRASIMPLETEMPN5,EOSEXTRASIMPLETEMPN4,EOSEXTRASIMPLETEMPN3,EOSEXTRASIMPLETEMPN2,EOSEXTRASIMPLETEMPN1,NUMEOSTEMPQUANTITIESMEM2);
#endif



// simple zoom
FTYPEEOS BASEEOSMAC(eossimplezoomtabledegen,NUMEOSDEGENQUANTITIESMEM1,EOSSIMPLEZOOMDEGENN5,EOSSIMPLEZOOMDEGENN4,EOSSIMPLEZOOMDEGENN3,EOSSIMPLEZOOMDEGENN2,EOSSIMPLEZOOMDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
FTYPEEOS BASEEOSMAC(eossimplezoomtablestandard,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSSTANDARDQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimplezoomtableguess,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSGUESSQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimplezoomtablediss,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSDISSQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimplezoomtabledp,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSDPQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimplezoomtablesden,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSSDENQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimplezoomtablesspec,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSSSPECQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimplezoomtablepofchi,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSPOFCHIQUANTITIESMEM);
FTYPEEOS BASEEOSMAC(eossimplezoomtabletemp,NUMEOSTEMPQUANTITIESMEM1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSTEMPQUANTITIESMEM2);

// different size for extra table
FTYPEEOS BASEEOSMAC(eossimplezoomtableextra,1,EOSEXTRASIMPLEZOOMN5,EOSEXTRASIMPLEZOOMN4,EOSEXTRASIMPLEZOOMN3,EOSEXTRASIMPLEZOOMN2,EOSEXTRASIMPLEZOOMN1,NUMEOSEXTRAQUANTITIESMEM);
#if(WHICHDATATYPEGENERAL==4)
FTYPEEOS BASEEOSMAC(eossimplezoomtableextradegen,NUMEOSDEGENQUANTITIESMEM1,EOSEXTRASIMPLEZOOMDEGENN5,EOSEXTRASIMPLEZOOMDEGENN4,EOSEXTRASIMPLEZOOMDEGENN3,EOSEXTRASIMPLEZOOMDEGENN2,EOSEXTRASIMPLEZOOMDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
FTYPEEOS BASEEOSMAC(eossimplezoomtableextratemp,NUMEOSTEMPQUANTITIESMEM1,EOSEXTRASIMPLEZOOMTEMPN5,EOSEXTRASIMPLEZOOMTEMPN4,EOSEXTRASIMPLEZOOMTEMPN3,EOSEXTRASIMPLEZOOMTEMPN2,EOSEXTRASIMPLEZOOMTEMPN1,NUMEOSTEMPQUANTITIESMEM2);
#endif

#endif // end if(WHICHEOS==KAZFULL)

////////////////////
//
// OPENMPMARK: These pointers can be static since pointers and globally shared values of EOS table
//
// Use regexp on above:
// 1) "FTYPEEOS BASEEOSMAC" -> "static FTYPEEOS PTRDEFEOSMAC"
// 2) remove #if's on any extra memory assignments so pointers always exist
//
////////////////////



// full
static FTYPEEOS PTRDEFEOSMAC(eosfulltabledegen,NUMEOSDEGENQUANTITIESMEM1,EOSFULLDEGENN5,EOSFULLDEGENN4,EOSFULLDEGENN3,EOSFULLDEGENN2,EOSFULLDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
static FTYPEEOS PTRDEFEOSMAC(eosfulltablestandard,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSSTANDARDQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eosfulltableguess,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSGUESSQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eosfulltablediss,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSDISSQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eosfulltabledp,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSDPQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eosfulltablesden,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSSDENQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eosfulltablesspec,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSSSPECQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eosfulltablepofchi,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSPOFCHIQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eosfulltabletemp,NUMEOSTEMPQUANTITIESMEM1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSTEMPQUANTITIESMEM2);

// different size for extra table
static FTYPEEOS PTRDEFEOSMAC(eosfulltableextra,1,EOSEXTRAFULLN5,EOSEXTRAFULLN4,EOSEXTRAFULLN3,EOSEXTRAFULLN2,EOSEXTRAFULLN1,NUMEOSEXTRAQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eosfulltableextradegen,NUMEOSDEGENQUANTITIESMEM1,EOSEXTRAFULLDEGENN5,EOSEXTRAFULLDEGENN4,EOSEXTRAFULLDEGENN3,EOSEXTRAFULLDEGENN2,EOSEXTRAFULLDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
static FTYPEEOS PTRDEFEOSMAC(eosfulltableextratemp,NUMEOSTEMPQUANTITIESMEM1,EOSEXTRAFULLTEMPN5,EOSEXTRAFULLTEMPN4,EOSEXTRAFULLTEMPN3,EOSEXTRAFULLTEMPN2,EOSEXTRAFULLTEMPN1,NUMEOSTEMPQUANTITIESMEM2);

// simple
static FTYPEEOS PTRDEFEOSMAC(eossimpletabledegen,NUMEOSDEGENQUANTITIESMEM1,EOSSIMPLEDEGENN5,EOSSIMPLEDEGENN4,EOSSIMPLEDEGENN3,EOSSIMPLEDEGENN2,EOSSIMPLEDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
static FTYPEEOS PTRDEFEOSMAC(eossimpletablestandard,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSSTANDARDQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimpletableguess,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSGUESSQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimpletablediss,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSDISSQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimpletabledp,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSDPQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimpletablesden,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSSDENQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimpletablesspec,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSSSPECQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimpletablepofchi,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSPOFCHIQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimpletabletemp,NUMEOSTEMPQUANTITIESMEM1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSTEMPQUANTITIESMEM2);

// different size for extra table
static FTYPEEOS PTRDEFEOSMAC(eossimpletableextra,1,EOSEXTRASIMPLEN5,EOSEXTRASIMPLEN4,EOSEXTRASIMPLEN3,EOSEXTRASIMPLEN2,EOSEXTRASIMPLEN1,NUMEOSEXTRAQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimpletableextradegen,NUMEOSDEGENQUANTITIESMEM1,EOSEXTRASIMPLEDEGENN5,EOSEXTRASIMPLEDEGENN4,EOSEXTRASIMPLEDEGENN3,EOSEXTRASIMPLEDEGENN2,EOSEXTRASIMPLEDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
static FTYPEEOS PTRDEFEOSMAC(eossimpletableextratemp,NUMEOSTEMPQUANTITIESMEM1,EOSEXTRASIMPLETEMPN5,EOSEXTRASIMPLETEMPN4,EOSEXTRASIMPLETEMPN3,EOSEXTRASIMPLETEMPN2,EOSEXTRASIMPLETEMPN1,NUMEOSTEMPQUANTITIESMEM2);


// simple zoom
static FTYPEEOS PTRDEFEOSMAC(eossimplezoomtabledegen,NUMEOSDEGENQUANTITIESMEM1,EOSSIMPLEZOOMDEGENN5,EOSSIMPLEZOOMDEGENN4,EOSSIMPLEZOOMDEGENN3,EOSSIMPLEZOOMDEGENN2,EOSSIMPLEZOOMDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
static FTYPEEOS PTRDEFEOSMAC(eossimplezoomtablestandard,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSSTANDARDQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimplezoomtableguess,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSGUESSQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimplezoomtablediss,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSDISSQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimplezoomtabledp,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSDPQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimplezoomtablesden,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSSDENQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimplezoomtablesspec,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSSSPECQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimplezoomtablepofchi,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSPOFCHIQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimplezoomtabletemp,NUMEOSTEMPQUANTITIESMEM1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSTEMPQUANTITIESMEM2);

// different size for extra table
static FTYPEEOS PTRDEFEOSMAC(eossimplezoomtableextra,1,EOSEXTRASIMPLEZOOMN5,EOSEXTRASIMPLEZOOMN4,EOSEXTRASIMPLEZOOMN3,EOSEXTRASIMPLEZOOMN2,EOSEXTRASIMPLEZOOMN1,NUMEOSEXTRAQUANTITIESMEM);
static FTYPEEOS PTRDEFEOSMAC(eossimplezoomtableextradegen,NUMEOSDEGENQUANTITIESMEM1,EOSEXTRASIMPLEZOOMDEGENN5,EOSEXTRASIMPLEZOOMDEGENN4,EOSEXTRASIMPLEZOOMDEGENN3,EOSEXTRASIMPLEZOOMDEGENN2,EOSEXTRASIMPLEZOOMDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
static FTYPEEOS PTRDEFEOSMAC(eossimplezoomtableextratemp,NUMEOSTEMPQUANTITIESMEM1,EOSEXTRASIMPLEZOOMTEMPN5,EOSEXTRASIMPLEZOOMTEMPN4,EOSEXTRASIMPLEZOOMTEMPN3,EOSEXTRASIMPLEZOOMTEMPN2,EOSEXTRASIMPLEZOOMTEMPN1,NUMEOSTEMPQUANTITIESMEM2);

