////////////////////////////////////
//
// Allocate space and setup pointers for EOS tablea
//
///////////////////////////////////////////////
//
// This entire file assumes all things are FTYPE except eostable itself that is explicitly double
//
///////////////////////////////////////////////

// presumed to be several functions as functions of 4 other quantities that are the independent variables (UEOS,PEOS,CHIEOS share same index)
// Notice that eostable has density as EOSN1 so fastest indicies are related to density and pressure-related quantities since this will result in fastest lookup for fixed H and Tdynorye
// due to float limit of 1E38, need doubles
// ,1,EOS??N5, at front is so table array uniform with degen table array


// most of the below is simple mod from copy/paste of first "full" table block
// Also change things in kazfulleos_set_arrays.c!  For that, can just take below BASEEOSMAC stuff and regexp one's way to required format as given in that C file.

// SUPERNOTE: Must create corresponding MPI_Bcast() for these in kazfulleos_read_setup_eostable.c !!


#if(WHICHEOS==KAZFULL)
// full
double BASEEOSMAC(eosfulltabledegen,NUMEOSDEGENQUANTITIESMEM1,EOSFULLDEGENN5,EOSFULLDEGENN4,EOSFULLDEGENN3,EOSFULLDEGENN2,EOSFULLDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
double BASEEOSMAC(eosfulltablestandard,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSSTANDARDQUANTITIESMEM);
double BASEEOSMAC(eosfulltableguess,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSGUESSQUANTITIESMEM);
double BASEEOSMAC(eosfulltablediss,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSDISSQUANTITIESMEM);
double BASEEOSMAC(eosfulltabledp,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSDPQUANTITIESMEM);
double BASEEOSMAC(eosfulltablesden,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSSDENQUANTITIESMEM);
double BASEEOSMAC(eosfulltablesspec,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSSSPECQUANTITIESMEM);
double BASEEOSMAC(eosfulltablepofchi,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSPOFCHIQUANTITIESMEM);
double BASEEOSMAC(eosfulltabletemp,NUMEOSTEMPQUANTITIESMEM1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSTEMPQUANTITIESMEM2);
double BASEEOSMAC(eosfulltableextra,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSEXTRAQUANTITIESMEM);

// simple
double BASEEOSMAC(eossimpletabledegen,NUMEOSDEGENQUANTITIESMEM1,EOSSIMPLEDEGENN5,EOSSIMPLEDEGENN4,EOSSIMPLEDEGENN3,EOSSIMPLEDEGENN2,EOSSIMPLEDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
double BASEEOSMAC(eossimpletablestandard,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSSTANDARDQUANTITIESMEM);
double BASEEOSMAC(eossimpletableguess,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSGUESSQUANTITIESMEM);
double BASEEOSMAC(eossimpletablediss,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSDISSQUANTITIESMEM);
double BASEEOSMAC(eossimpletabledp,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSDPQUANTITIESMEM);
double BASEEOSMAC(eossimpletablesden,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSSDENQUANTITIESMEM);
double BASEEOSMAC(eossimpletablesspec,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSSSPECQUANTITIESMEM);
double BASEEOSMAC(eossimpletablepofchi,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSPOFCHIQUANTITIESMEM);
double BASEEOSMAC(eossimpletabletemp,NUMEOSTEMPQUANTITIESMEM1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSTEMPQUANTITIESMEM2);
double BASEEOSMAC(eossimpletableextra,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSEXTRAQUANTITIESMEM);

// simple zoom
double BASEEOSMAC(eossimplezoomtabledegen,NUMEOSDEGENQUANTITIESMEM1,EOSSIMPLEZOOMDEGENN5,EOSSIMPLEZOOMDEGENN4,EOSSIMPLEZOOMDEGENN3,EOSSIMPLEZOOMDEGENN2,EOSSIMPLEZOOMDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
double BASEEOSMAC(eossimplezoomtablestandard,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSSTANDARDQUANTITIESMEM);
double BASEEOSMAC(eossimplezoomtableguess,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSGUESSQUANTITIESMEM);
double BASEEOSMAC(eossimplezoomtablediss,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSDISSQUANTITIESMEM);
double BASEEOSMAC(eossimplezoomtabledp,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSDPQUANTITIESMEM);
double BASEEOSMAC(eossimplezoomtablesden,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSSDENQUANTITIESMEM);
double BASEEOSMAC(eossimplezoomtablesspec,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSSSPECQUANTITIESMEM);
double BASEEOSMAC(eossimplezoomtablepofchi,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSPOFCHIQUANTITIESMEM);
double BASEEOSMAC(eossimplezoomtabletemp,NUMEOSTEMPQUANTITIESMEM1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSTEMPQUANTITIESMEM2);
double BASEEOSMAC(eossimplezoomtableextra,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSEXTRAQUANTITIESMEM);
#endif

////////////////////
//
// OPENMPMARK: These pointers can be static since pointers and globally shared values of EOS table
//
////////////////////

// full
static double PTRDEFEOSMAC(eosfulltabledegen,NUMEOSDEGENQUANTITIESMEM1,EOSFULLDEGENN5,EOSFULLDEGENN4,EOSFULLDEGENN3,EOSFULLDEGENN2,EOSFULLDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
static double PTRDEFEOSMAC(eosfulltablestandard,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSSTANDARDQUANTITIESMEM);
static double PTRDEFEOSMAC(eosfulltableguess,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSGUESSQUANTITIESMEM);
static double PTRDEFEOSMAC(eosfulltablediss,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSDISSQUANTITIESMEM);
static double PTRDEFEOSMAC(eosfulltabledp,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSDPQUANTITIESMEM);
static double PTRDEFEOSMAC(eosfulltablesden,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSSDENQUANTITIESMEM);
static double PTRDEFEOSMAC(eosfulltablesspec,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSSSPECQUANTITIESMEM);
static double PTRDEFEOSMAC(eosfulltablepofchi,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSPOFCHIQUANTITIESMEM);
static double PTRDEFEOSMAC(eosfulltabletemp,NUMEOSTEMPQUANTITIESMEM1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSTEMPQUANTITIESMEM2);
static double PTRDEFEOSMAC(eosfulltableextra,1,EOSFULLN5,EOSFULLN4,EOSFULLN3,EOSFULLN2,EOSFULLN1,NUMEOSEXTRAQUANTITIESMEM);

// simple
static double PTRDEFEOSMAC(eossimpletabledegen,NUMEOSDEGENQUANTITIESMEM1,EOSSIMPLEDEGENN5,EOSSIMPLEDEGENN4,EOSSIMPLEDEGENN3,EOSSIMPLEDEGENN2,EOSSIMPLEDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
static double PTRDEFEOSMAC(eossimpletablestandard,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSSTANDARDQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimpletableguess,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSGUESSQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimpletablediss,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSDISSQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimpletabledp,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSDPQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimpletablesden,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSSDENQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimpletablesspec,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSSSPECQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimpletablepofchi,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSPOFCHIQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimpletabletemp,NUMEOSTEMPQUANTITIESMEM1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSTEMPQUANTITIESMEM2);
static double PTRDEFEOSMAC(eossimpletableextra,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSEXTRAQUANTITIESMEM);

// simple zoom
static double PTRDEFEOSMAC(eossimplezoomtabledegen,NUMEOSDEGENQUANTITIESMEM1,EOSSIMPLEZOOMDEGENN5,EOSSIMPLEZOOMDEGENN4,EOSSIMPLEZOOMDEGENN3,EOSSIMPLEZOOMDEGENN2,EOSSIMPLEZOOMDEGENN1,NUMEOSDEGENQUANTITIESMEM2);
static double PTRDEFEOSMAC(eossimplezoomtablestandard,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSSTANDARDQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimplezoomtableguess,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSGUESSQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimplezoomtablediss,1,EOSSIMPLEN5,EOSSIMPLEN4,EOSSIMPLEN3,EOSSIMPLEN2,EOSSIMPLEN1,NUMEOSDISSQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimplezoomtabledp,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSDPQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimplezoomtablesden,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSSDENQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimplezoomtablesspec,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSSSPECQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimplezoomtablepofchi,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSPOFCHIQUANTITIESMEM);
static double PTRDEFEOSMAC(eossimplezoomtabletemp,NUMEOSTEMPQUANTITIESMEM1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSTEMPQUANTITIESMEM2);
static double PTRDEFEOSMAC(eossimplezoomtableextra,1,EOSSIMPLEZOOMN5,EOSSIMPLEZOOMN4,EOSSIMPLEZOOMN3,EOSSIMPLEZOOMN2,EOSSIMPLEZOOMN1,NUMEOSEXTRAQUANTITIESMEM);



