

#define lenCGS2GU(x)    (x/MASSCM )
#define lenGU2CGS(x)    (x*MASSCM )
#define timeCGS2GU(x)   (x/MASSCM*CCCTRUE)
#define timeGU2CGS(x)   (x*MASSCM/CCCTRUE)
#define velCGS2GU(x)    (x/CCCTRUE)
#define velGU2CGS(x)    (x*CCCTRUE)
#define rhoCGS2GU(x)    (x*GGG/CCCTRUE/CCCTRUE*MASSCM*MASSCM*MASSCM)
#define rhoGU2CGS(x)    (x/GGG*CCCTRUE*CCCTRUE/MASSCM/MASSCM/MASSCM)
#define massCGS2GU(x)    (x*GGG/CCCTRUE/CCCTRUE)
#define massGU2CGS(x)    (x/GGG*CCCTRUE*CCCTRUE)
#define kappaGU2CGS(x)  (x*GGG/CCCTRUE/CCCTRUE*MASSCM*MASSCM)
#define kappaCGS2GU(x)  (x/GGG*CCCTRUE*CCCTRUE/MASSCM/MASSCM)
#define endenCGS2GU(x) (x*GGG*MASSCM*MASSCM*MASSCM/CCCTRUE/CCCTRUE/CCCTRUE/CCCTRUE)
#define endenGU2CGS(x) (x/GGG/MASSCM/MASSCM/MASSCM*CCCTRUE*CCCTRUE*CCCTRUE*CCCTRUE)
#define fluxCGS2GU(x) (x*GGG*MASSCM*MASSCM*MASSCM/CCCTRUE/CCCTRUE/CCCTRUE/CCCTRUE/CCCTRUE)
#define fluxGU2CGS(x) (x/GGG/MASSCM/MASSCM/MASSCM*CCCTRUE*CCCTRUE*CCCTRUE*CCCTRUE*CCCTRUE)










