#define GGG (6.674e-8)
#define CCCTRUE 2.998e10
#define MSUNCM 147700.

#define K_BOLTZ (1.3806488e-16L * GGG / CCCTRUE / CCCTRUE / CCCTRUE / CCCTRUE  )
#define M_PROTON (1.67262158e-24L * GGG / CCCTRUE / CCCTRUE)
#define SIGMA_RAD (5.67e-5 * GGG / CCCTRUE / CCCTRUE / CCCTRUE / CCCTRUE / CCCTRUE * MASSCM * MASSCM  * MASSCM)
//efine A_RAD (4.*5.67e-5/CCCTRUE * GGG / CCCTRUE / CCCTRUE / CCCTRUE / CCCTRUE)
#define MU_GAS 1.
#define Z_RATIO (1.0)
#define Pi (3.141592654)     

#define EFLOOR SMALL
#define RADEPS (1.e-6)
#define RADCONV (1.e-7)

#define PRADEPS (1.e-6)
#define PRADCONV (1.e-8)


#define lenCGS2GU(x)    (x/MASSCM )
#define lenGU2CGS(x)    (x*MASSCM )
#define timeCGS2GU(x)   (x/MASSCM*CCCTRUE)
#define timeGU2CGS(x)   (x*MASSCM/CCCTRUE)
#define velCGS2GU(x)    (x/CCCTRUE)
#define velGU2CGS(x)    (x*CCCTRUE)
#define rhoCGS2GU(x)    (x*GGG/CCCTRUE/CCCTRUE*MASSCM*MASSCM*MASSCM)
#define rhoGU2CGS(x)    (x/GGG*CCCTRUE*CCCTRUE/MASSCM/MASSCM/MASSCM)
#define massCGS2GU(x)    (x*GGG/CCCTRUE/CCCTRUE)
#define massGU2CGS(x)    (x/GGG*CCCTRUE*CCCTRUE)
#define kappaGU2CGS(x)  (x*GGG/CCCTRUE/CCCTRUE*MASSCM*MASSCM)
#define kappaCGS2GU(x)  (x/GGG*CCCTRUE*CCCTRUE/MASSCM/MASSCM)
#define endenCGS2GU(x) (x*GGG*MASSCM*MASSCM*MASSCM/CCCTRUE/CCCTRUE/CCCTRUE/CCCTRUE)
#define endenGU2CGS(x) (x/GGG/MASSCM/MASSCM/MASSCM*CCCTRUE*CCCTRUE*CCCTRUE*CCCTRUE)
#define fluxCGS2GU(x) (x*GGG*MASSCM*MASSCM*MASSCM/CCCTRUE/CCCTRUE/CCCTRUE/CCCTRUE/CCCTRUE)
#define fluxGU2CGS(x) (x/GGG/MASSCM/MASSCM/MASSCM*CCCTRUE*CCCTRUE*CCCTRUE*CCCTRUE*CCCTRUE)

#define KAPPA_ES_COEFF (kappaCGS2GU(0.4))
#define KAPPA_FF_COEFF (1.7e-25/1.67262158e-24/1.67262158e-24*CCCTRUE*CCCTRUE*CCCTRUE*CCCTRUE/GGG/GGG/MASSCM/MASSCM/MASSCM/MASSCM/MASSCM)
#define KAPPA_BF_COEFF (4.8e-24/1.67262158e-24/1.67262158e-24*CCCTRUE*CCCTRUE*CCCTRUE*CCCTRUE/GGG/GGG/MASSCM/MASSCM/MASSCM/MASSCM/MASSCM)









