
SRCSJONINTERP = \
jon_interp.c \
jon_interp_computepreprocess.c  jon_interp_filter.c jon_interp_interpolationitself.c jon_interp_mnewt.c jon_interp_newt.c \
nrutil2.c coord.c nrutil.c ludcmp.c lubksb.c lnsrch.c fdjac.c fmin.c broydn.c qrdcmp.c rsolv.c qrupdt.c rotate.c ranc.c bcucof.c bcuint.c metric.tools.c mpi_fprintfs.c gaussj.c tetrad.c tetlapack_func_doubleonly.c
#END

OBJSJONINTERP = \
jon_interp.o \
jon_interp_computepreprocess.o  jon_interp_filter.o jon_interp_interpolationitself.o jon_interp_mnewt.o  jon_interp_newt.o \
nrutil2.o coord.o nrutil.o ludcmp.o lubksb.o lnsrch.o fdjac.o fmin.o broydn.o qrdcmp.o rsolv.o qrupdt.o rotate.o ranc.o bcucof.o bcuint.o metric.tools.o mpi_fprintfs.o gaussj.o tetrad.o  tetlapack_func_doubleonly.o
#END

