
/*! \file superdefs.pointers.rad.h
    \brief Large array pointers for Koral/RADIATION
*/

/*! \file superdecs.pointers.rad.h
    \brief AUTOGENERATED from superdefs.pointers.rad.h
*/


// KORAL
FTYPE PTRDEFGLOBALMETMACP2A2(tlab2ortho,BOOSTGRIDPOS,BOOSTDIRS,N1M+SHIFT1,N2M+SHIFT2,N3M+SHIFT3,NDIM,NDIM);

int PTRDEFGLOBALMACP0A1(prioritermethod,N1M+SHIFT1,N2M+SHIFT2,N3M+SHIFT3,NUMPRIORITERMETHODINDEX);

FTYPE PTRDEFGLOBALMACP1A1(Mradk,FILL,N1M,N2M,N3M,NPR);

//FTYPE *u,*x,*xb,*du,*ut1,*ut2,*ut3,*ut4,*ut0,*u_bak,*u_step1,*u_step2,*u_step3,*u_step4,*ahdx,*ahdy,*ahdz,*aradx,*arady,*aradz,
//  *ahdxl,*ahdyl,*ahdzl,*aradxl,*aradyl,*aradzl,  *ahdxr,*ahdyr,*ahdzr,*aradxr,*aradyr,*aradzr,*p,*pt0,*px,*py,*pz,*s,*g,*gbx,*gby,*gbz,*Gbx,*Gby,*Gbz,
//  *pbLx,*pbRx,*pbLy,*pbRy,*pbLz,*pbRz,*sbLx,*sbRx,*sbLy,*sbRy,*sbLz,*sbRz,*ubLx,*ubRx,*ubLy,*ubRy,*ubLz,*ubRz,
//  *flbx,*flby,*flbz,*flLx,*flRx,*flLy,*flRy,*flLz,*flRz,*gKr,*gKrbx,*gKrby,*gKrbz,*G,*tmuup,*tmudn,*tmuupbx,*tmudnbx,*tmuupby,*tmudnby,*tmuupbz,*tmudnbz;
//int *cellflag,**loop_1,**loop_2,Nloop_1,Nloop_2;
// FTYPE Kr_tmp[4][4][4],g_tmp[4][4];
//FTYPE inputarg[10];
//int **gcidx;


//FTYPE max_ws[3],max_dt;
//FTYPE min_dx,min_dy,min_dz;
  

//FILE *fout1,*fout_totmass;
//int nfout1;

