

FTYPE BASEMACP0A1(pglobal,N1M,N2M,N3M,NPR);  /* space for primitive vars */
FTYPE BASEMETMACP1A2(gcon,NPG,N1M+SHIFT1,N2M+SHIFT2,N3M+SHIFT3,NDIM,NDIM);
FTYPE BASEMETMACP0A3(conn,N1M,N2M,N3M,NDIM,NDIM,NDIM);




